package com.atenea.talentmixer.models.entities;

// default package
// Generated 28 mar 2023 11:57:20 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project")
public class Project implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private UserAccount userAccount;
	private String title;
	private String summary;
	private String description;
	private Date createdAt;
	private String image;

	public Project() {
	}

	public Project(int id, UserAccount userAccount, String title, String summary, String description, Date createdAt) {
		this.id = id;
		this.userAccount = userAccount;
		this.title = title;
		this.summary = summary;
		this.description = description;
		this.createdAt = createdAt;
	}

	public Project(int id, UserAccount userAccount, String title, String summary, String description, Date createdAt,
			String image) {
		this.id = id;
		this.userAccount = userAccount;
		this.title = title;
		this.summary = summary;
		this.description = description;
		this.createdAt = createdAt;
		this.image = image;
	}
	public Project(Project p) {
		this.id = p.id;
		this.userAccount = p.userAccount;
		this.title = p.title;
		this.summary = p.summary;
		this.description = p.description;
		this.createdAt = p.createdAt;
		this.image = p.image;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user_account", nullable = false)
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@Column(name = "title", nullable = false, length = 150)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "summary", nullable = false, length = 300)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "description", nullable = false, length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "image", length = 2000)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
