package com.atenea.talentmixer.models.entities;

// default package
// Generated 28 mar 2023 11:57:20 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project")
public class Project implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String title;
	private String summary;
	private String description;
	private Date createdAt;
	private String image;
	private int idUserAccount;

	public Project() {
	}

	public Project(int id, String title, String summary, String description, Date createdAt, int idUserAccount) {
		this.id = id;
		this.title = title;
		this.summary = summary;
		this.description = description;
		this.createdAt = createdAt;
		this.idUserAccount = idUserAccount;
	}

	public Project(int id, String title, String summary, String description, Date createdAt, int idUserAccount,
			String image) {
		this.id = id;
		this.title = title;
		this.summary = summary;
		this.description = description;
		this.createdAt = createdAt;
		this.image = image;
		this.idUserAccount = idUserAccount;

	}
	
	public Project(Project p) {
		this.id = p.id;
		this.title = p.title;
		this.summary = p.summary;
		this.description = p.description;
		this.createdAt = p.createdAt;
		this.image = p.image;
		this.idUserAccount = p.idUserAccount;

	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 150)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "summary", nullable = false, length = 300)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "description", nullable = false, length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "image", length = 2000)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public int getIdUserAccount() {
		return idUserAccount;
	}

	public void setIdUserAccount(int idUserAccount) {
		this.idUserAccount = idUserAccount;
	}
	
	

}
