package com.atenea.talentmixer.models.entity;

// default package
// Generated 25 mar 2023 12:17:13 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project")
public class Project implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private String tittle;
	private String summary;
	private String description;
	private Date createdAt;
	private String image;

	public Project() {
	}

	public Project(int id, String tittle, String summary, String description, Date createdAt) {
		this.id = id;
		this.tittle = tittle;
		this.summary = summary;
		this.description = description;
		this.createdAt = createdAt;
	}

	public Project(int id, String tittle, String summary, String description, Date createdAt, String image) {
		this.id = id;
		this.tittle = tittle;
		this.summary = summary;
		this.description = description;
		this.createdAt = createdAt;
		this.image = image;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tittle", nullable = false, length = 150)
	public String getTittle() {
		return this.tittle;
	}

	public void setTittle(String tittle) {
		this.tittle = tittle;
	}

	@Column(name = "summary", nullable = false, length = 300)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "description", nullable = false, length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "image", length = 2000)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
